# Generated by Django 3.1.5 on 2021-03-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogPosts',
            new_name='blogPost',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='conteny',
            new_name='content',
        ),
    ]
